/*
 *  arch/i386/sys/types.h
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2024 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

/*
 *  POSIX 1003.1 types
 */
#ifndef _DEV_T_DEFINED_
 #define _DEV_T_DEFINED_
 typedef unsigned long  dev_t;  /* Combination of node and device   */
#endif
#ifndef _INO_T_DEFINED_
 #define _INO_T_DEFINED_
 typedef unsigned long  ino_t;  /* Used for file serial numbers     */
#endif
#ifndef _MODE_T_DEFINED_
 #define _MODE_T_DEFINED_
 typedef unsigned short mode_t; /* Used for some file attributes    */
#endif
#ifndef _NLINK_T_DEFINED_
 #define _NLINK_T_DEFINED_
 typedef unsigned short nlink_t;/* Used for link counts             */
#endif
#ifndef _UID_T_DEFINED_
 #define _UID_T_DEFINED_
 typedef unsigned short uid_t;  /* Used for user IDs                */
#endif
#ifndef _GID_T_DEFINED_
 #define _GID_T_DEFINED_
 typedef unsigned short gid_t;  /* Used for group IDs               */
#endif
#ifndef _BLKSIZE_T_DEFINED_
 #define _BLKSIZE_T_DEFINED_
 typedef unsigned long  blksize_t;
#endif
#ifndef _BLKCNT_T_DEFINED_
 #define _BLKCNT_T_DEFINED_
 typedef unsigned long  blkcnt_t;
#endif
#ifndef _ID_T_DEFINED_
 #define _ID_T_DEFINED_
 typedef int            id_t;   /* Generic ID, may be uid, gid, pid */
#endif

typedef char            *caddr_t;
typedef long            daddr_t;
