@echo off
echo Open Watcom Build Environment
PATH C:\WATCOM\BINW;%PATH%
SET INCLUDE=C:\WATCOM\H;%INCLUDE%
SET WATCOM=C:\WATCOM
SET EDPATH=C:\WATCOM\EDDAT
SET WWINHELP=C:\WATCOM\BINW
SET WIPFC=C:\WATCOM\WIPFC
