/*
 *  dderror.h   Error definitions for portable video miniports.
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2024 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file
#endif

#ifndef _DDERROR_
#define _DDERROR_

#define _WINERROR_

#define NO_ERROR				0L
#define ERROR_INVALID_FUNCTION			1L
#define ERROR_NOT_ENOUGH_MEMORY			8L
#define ERROR_DEV_NOT_EXIST			55L
#define ERROR_INVALID_PARAMETER			87L
#define ERROR_INSUFFICIENT_BUFFER		122L
#define ERROR_INVALID_NAME			123L
#define ERROR_BUSY				170L
#define ERROR_MORE_DATA				234L
#define WAIT_TIMEOUT				258L
#define ERROR_IO_PENDING			997L
#define ERROR_DEVICE_INITIALIZATION_NEEDED	1164L
#define ERROR_CONTINUE				1246L
#define ERROR_NO_MORE_DEVICES			1248L

#endif
