/*
 *  usb100.h    Backward compatibility header
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2024 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef __USB100_H__
#define __USB100_H__

#include "usbspec.h"

#endif /* __USB100_H__ */
