/*
 *  cguid.h     COM GUIDs
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2024 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef __CGUID_H__
#define __CGUID_H__

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file
#endif

/* GUIDs */
EXTERN_C const IID  __cdecl GUID_NULL;

#endif /* __CGUID_H__ */
