/*
 *  winres.h    Extra Win32 resource definitions
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2024 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file
#endif

/* Define default Windows version number. */
#ifndef WINVER
    #define WINVER          0x0400
#endif

#include <winresrc.h>

/* Version information resource identifier */
#define VS_VERSION_INFO 1

/* Selected control messages */
#define LB_ADDSTRING    (WM_USER + 1)
#define CB_ADDSTRING    (WM_USER + 3)

/* Special control identifier for static text */
#undef IDC_STATIC
#define IDC_STATIC  (-1)
