/*
 *  winresrc.h  Win32 main resource header file
 *
 * =========================================================================
 *
 *                          Open Watcom Project
 *
 * Copyright (c) 2004-2024 The Open Watcom Contributors. All Rights Reserved.
 *
 *    This file is automatically generated. Do not edit directly.
 *
 * =========================================================================
 */

#ifndef _WINRESRC_
#define _WINRESRC_

#ifndef _ENABLE_AUTODEPEND
 #pragma read_only_file
#endif

/* Define default version numbers. */
#ifndef WINVER
    #define WINVER          0x0400
#endif
#ifndef _WIN32_WINNT
    #define _WIN32_WINNT    0x0400
#endif
#ifndef _WIN32_IE
    #define _WIN32_IE       0x0400
#endif
#ifndef _WIN32_WINDOWS
    #define _WIN32_WINDOWS  0x0400
#endif

#include <winuser.rh>
#include <commctrl.rh>
#include <dde.rh>
#include <winnt.rh>
#include <dlgs.h>
#include <winver.h>

#endif /* _WINRESRC_ */
