; PROTOCOL.INI for LANtastic 8.0
;------------------------------------------
;---- Contains sections for:
;----      Protocol Manager
;----      NodeRunner and AE-series adapters
;----      HP Jet Direct support
;----      SMB connections
;
; (this is a complete file, not a fragment)
;
[PROTMAN]  
Priority = NETBEUI
  DriverName = PROTMAN$
  Dynamic = Yes

[NETBEUI_XIF]
  DriverName = NetBEUI$
  Sessions = 6
  NCBS = 12
  Bindings = NEX000_NIF
  LANABASE = 1

[MS$DLC]
  Drivername=MSDLC$
  BufQElements=128
  DlcRetries=5
  Stations=7
  ;Change line below to swap=1 for token ring adapters
  Swap=0
  ;Change line below to saps=<number of printer tasks>
  Saps=7
  Bindings=NEX000_NIF

[NEX000_NIF]
  DriverName = NEX000$

;---------------
; IOBase = 0x300
;
;
; I/O base address for AEX adapters (always required) or 
;     NodeRunner adapters (optional in single adapter configurations)
;
; This parameter specifies the input/output port base address
; of the network adapter card. The specified value must match the
; setting of the network adapter card. On Artisoft NodeRunner
; Ethernet adapters, this parameter is not required, and is
; determined automatically. This parameter is always required
; in multi-adapter configurations.
;
; Valid values are 0x300, 0x320, 0x340, 0x360, 0x1000, 0x2020, and 0x8020."

;---------------
; IRQ = 15
;
; Interrupt level for AEX adapters (always required) or 
;     NodeRunner adapters (optional in single adapter configurations)
;
; This parameter specifies the interrupt request level (IRQ)
; of the network adapter card. The specified value must match the
; setting of the network adapter card. On Artisoft NodeRunner Ethernet
; adapters, this parameter is not required, and is determined
; automatically. Refer to your adapter documentation for a list of I/O base
; addresses and their corresponding default interrupt request levels.
;
; Valid values are 2, 3, 4, 5, 6, 7, 9, 10, and 15."
