// resource.h : Defines the resource constants for the Test Server
//              application.
//
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) 1992 Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and Microsoft
// QuickHelp documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.
//
// Note that this window only contains #define directives.  This makes it
// suitable for including in the testclnt.rc resource file.

#ifndef __RESOURCE_H__
#define __RESOURCE_H__

// Object Edit Control Values
#define IDC_OK          101
#define IDC_CANCEL      102
#define IDC_EDIT        103
#define IDC_TITLE       104
#define IDC_TEXT        105
#define IDC_LIST        106

// File Menu Item Values
#define IDM_NEW         200
#define IDM_OPEN        201
#define IDM_SAVE        202
#define IDM_SAVEAS      203
#define IDM_UPDATE      204
#define IDM_EXIT        205

// Edit Menu Item Values
#define IDM_COPYLINK    300
#define IDM_COPYOBJECT  301

// Test Menu Item Values
#define IDM_LOGGING     400
#define IDM_REVOKESVR   401
#define IDM_REVOKEDOC   402
#define IDM_REVERTDOC   403
#define IDM_SAVEDOC     404
#define IDM_CLOSEDOC    405
#define IDM_CHANGEDOC   406
#define IDM_CHANGEITEM  407

// Help Menu Item Values
#define IDM_ABOUT       500

// Dialog Values
#define IDDT_ABOUT      1000
#define IDDT_EDIT       1001

#endif // __RESOURCE_H__

