# Makefile : Builds the restool application
#
# Usage:     NMAKE option (build restool)
#    or:     NMAKE clean  (erase all compiled files)
#
# options:   DEBUG=[0|1]  (DEBUG not defined is equivalent to DEBUG=0)
#
# This is a part of the Microsoft Foundation Classes C++ library.
# Copyright (C) 1992 Microsoft Corporation
# All rights reserved.
#
# This source code is only intended as a supplement to the
# Microsoft Foundation Classes Reference and Microsoft
# QuickHelp documentation provided with the library.
# See these sources for detailed information regarding the
# Microsoft Foundation Classes product.
#

CPPFLAGS=/AM /W3 /Zp /D_DOS
LINKFLAGS=/NOD /ONERROR:NOEXE

!if "$(DEBUG)"=="1"
CPPFLAGS=/D_DEBUG $(CPPFLAGS) /Od /Zi /f
LINKFLAGS=$(LINKFLAGS) /COD
LIBS=mafxcrd mlibce
!else
CPPFLAGS=$(CPPFLAGS) /Oselg /Gs
LINKFLAGS=$(LINKFLAGS)  
LIBS=mafxcr mlibce
!endif

restool.exe:     restool.obj
	link $(LINKFLAGS) restool, restool, NUL, $(LIBS);

restool.obj:    dlgres.h

clean:
		-erase restool.exe
		-erase restool.obj
